Move autopostgresqlbackup to a template
- Add a trap function which sends a passive check to Nagios
- If the script reaches the end and still has $STATUS of 0,
  assume that it has succeeded

diff --git a/modules/govuk_postgresql/templates/etc/cron.daily/autopostgresqlbackup.erb b/modules/govuk_postgresql/templates/etc/cron.daily/autopostgresqlbackup.erb
--- a/modules/govuk_postgresql/templates/etc/cron.daily/autopostgresqlbackup.erb
+++ b/modules/govuk_postgresql/templates/etc/cron.daily/autopostgresqlbackup.erb
@@ -1,4 +1,19 @@
 #!/bin/bash
+
+set -e
+
+# The default Icinga passive alert assumes that the script failed
+NAGIOS_CODE=2
+NAGIOS_MESSAGE="CRITICAL: PostgreSQL backup failed"
+
+# Triggered whenever this script exits, successful or otherwise. The values
+# of CODE/MESSAGE will be taken from that point in time.
+function nagios_passive () {
+  printf "<%= @fqdn %>\t<%= @service_desc %>\t${NAGIOS_CODE}\t${NAGIOS_MESSAGE}\n" | /usr/sbin/send_nsca -H alert.cluster >/dev/null
+}
+
+trap nagios_passive EXIT
+
 #
 # PostgreSQL Backup Script Ver 1.0
 # http://autopgsqlbackup.frozenpc.net
@@ -625,5 +640,10 @@ fi
 # Clean up Logfile
 rm -f "$LOGFILE"
 rm -f "$LOGERR"
+
+if [ $STATUS -eq 0 ]; then
+  NAGIOS_CODE=0
+  NAGIOS_MESSAGE="OK: PostgreSQL backup succeeded"
+fi
 
 exit $STATUS
