Add Icinga passive check for script running
We should ensure that the script continues to successfully run for the
import of transition logs rather than relying on people manually
checking transition stats.

diff --git a/modules/govuk_cdnlogs/templates/process_transition_logs.erb b/modules/govuk_cdnlogs/templates/process_transition_logs.erb
--- a/modules/govuk_cdnlogs/templates/process_transition_logs.erb
+++ b/modules/govuk_cdnlogs/templates/process_transition_logs.erb
@@ -4,6 +4,18 @@
 # two repositories used here.
 
 set -e
+<% if @enable_cron %>
+# Defaults, assumed failed.
+NAGIOS_CODE=2
+NAGIOS_MESSAGE="CRITICAL: Transition logs processing script not running"
+
+# Triggered whenever this script exits, successful or otherwise. The values
+# of CODE/MESSAGE will be taken from that point in time.
+function nagios_passive () {
+  printf "<%= @ipaddress_eth0 %>\t<%= @service_desc %>\t${NAGIOS_CODE}\t${NAGIOS_MESSAGE}\n" | /usr/sbin/send_nsca -H alert.cluster >/dev/null
+}
+trap nagios_passive EXIT
+<% end %>
 
 # Ensure we're working from the user directory
 cd /home/<%= @user %>
@@ -53,4 +65,9 @@ if ! git diff --cached --quiet; then
 fi
 <% if @enable_cron %>
 git push origin master
+
+if [ $? == 0 ]; then
+  NAGIOS_CODE=0
+  NAGIOS_MESSAGE="OK: Transition logs processing script successful"
+fi
 <% end %>
