[#84681958] Add passive check for MongoDB backup
We currently have no alerting if the MongoDB backup fails. This commit
adds a passive check to the automongodbbackup script which sends
a critical alert to Icinga if the backup fails.

diff --git a/modules/mongodb/templates/automongodbbackup b/modules/mongodb/templates/automongodbbackup
--- a/modules/mongodb/templates/automongodbbackup
+++ b/modules/mongodb/templates/automongodbbackup
@@ -1,4 +1,19 @@
 #!/bin/bash
+
+set -e
+
+# The default Icinga passive alert assumes that the script failed
+NAGIOS_CODE=2
+NAGIOS_MESSAGE="CRITICAL: MongoDB backup failed"
+
+# Triggered whenever this script exits, successful or otherwise. The values
+# of CODE/MESSAGE will be taken from that point in time.
+function nagios_passive () {
+  printf "<%= @fqdn %>\t<%= @service_desc %>\t${NAGIOS_CODE}\t${NAGIOS_MESSAGE}\n" | /usr/sbin/send_nsca -H alert.cluster >/dev/null
+}
+
+trap nagios_passive EXIT
+
 #
 # MongoDB Backup Script
 # VER. 0.9
@@ -565,6 +580,8 @@ if [ $STATUS -gt 0 ];
 then
   logger -t $APPNAME "$APPNAME wrote to STDERR. This may indicate an issue. Completed in T:$TOTALTIME seconds"
 else
+  NAGIOS_CODE=0
+  NAGIOS_MESSAGE="OK: MongoDB backup succeeded"
   logger -t $APPNAME "$APPNAME completed in T:$TOTALTIME seconds"
 fi
 exit $STATUS
