Mongodb s3 backups 1
What
Inconsistent errors while performing s3 backups for trailing slashes not being present at the end
of bucket URLs.
As a result of of the errors the script never gets to a point where it can cleanup the tarball(s) it
creates causing the host to run low on disk space.
s3 backups are gated in the base backup class but are currently deployed and performed on every provisioned
with mongodb in integration.

How
Add trailing slash to bucket directories/URLs as manual tests show the script works with or without trailing
slash.
Implemnt trap in bash script which calls a function that performs housekeeping regardless of the exit status.
Removed gated boolean value from common integartion data. Applied the value in node specific files in hiera.

diff --git a/modules/mongodb/templates/mongodb-backup-s3.erb b/modules/mongodb/templates/mongodb-backup-s3.erb
--- a/modules/mongodb/templates/mongodb-backup-s3.erb
+++ b/modules/mongodb/templates/mongodb-backup-s3.erb
@@ -12,8 +12,8 @@ BACKUP_NODE=<%= @backup_node %>
 BACKUP_DIR=<%= @backup_dir %>
 BACKUP_FILE=mongodump-<%= @fqdn %>.$(date +%F_%T).tar.gz.gpg
 KEY_FINGERPRINT=<%= @private_gpg_key_fingerprint %>
-S3_BUCKET=<%= @s3_bucket %>/<%= @fqdn %>
-S3_BUCKET_DAILY=<%= @s3_bucket_daily %>/<%= @fqdn %>
+S3_BUCKET=<%= @s3_bucket %>/<%= @fqdn %>/
+S3_BUCKET_DAILY=<%= @s3_bucket_daily %>/<%= @fqdn %>/
 
 # Triggered whenever this script exits, successful or otherwise. The values
 # of CODE/MESSAGE will be taken from that point in time.
@@ -22,6 +22,13 @@ printf "<%= @ipaddress %>\t<%= @service_desc %>\t${NAGIOS_CODE}\t${NAGIOS_MESSAG
 }
 
 trap nagios_passive EXIT
+
+# Remove any tarballs created as a result of running this script regardless of the exit status
+function housekeeping() {
+  /bin/rm -f $BACKUP_DIR/mongodump-*
+}
+
+trap housekeeping EXIT
 
 # Backup mongodb
 TIME="$(date +%s)"
@@ -46,8 +53,6 @@ fi
 TIME="$(($(date +%s)-TIME))"
 printf "BACKUP UPLOADED IN: ${TIME}s\n"
 
-# Tidy up
-/bin/rm -f $BACKUP_DIR/mongodump-*
 
 if [ $? == 0 ]; then
   STATUS=0
