Update akamai pull logs script to use SFTP

diff --git a/modules/akamai_logs/templates/pull_logs.sh.erb b/modules/akamai_logs/templates/pull_logs.sh.erb
--- a/modules/akamai_logs/templates/pull_logs.sh.erb
+++ b/modules/akamai_logs/templates/pull_logs.sh.erb
@@ -1,23 +1,27 @@
-#! /bin/sh
+#! /bin/bash
 # Pulls the log files from Akamai
 set -x
 
 LOCAL_DOWNLOAD_DIR=<%= @local_logs_dir %>/tmp
 LOCAL_LOGS_DIR=<%= @local_logs_dir %>/logs
-LOCAL_MD5=/usr/bin/md5sum
 
 AKAMAI_USER=<%= @akamai_user %>
 AKAMAI_HOST=<%= @akamai_host %>
 AKAMAI_LOGS_DIR=<%= @path_to_logs %>
-AKAMAI_MD5=/usr/bin/md5sum
 
-BACKUP_USER=<%= @user %>
-BACKUP_HOST=localhost
+BACKUP_USER=<%= @backup_user %>
+BACKUP_HOST=<%= @backup_host %>
 BACKUP_LOGS_DIR=<%= @local_logs_dir %>
-BACKUP_MD5=/usr/bin/md5sum
 
-LOCK_FILE=$LOCAL_DOWNLOADS_DIR/.lock
-CHECKSUM_FILE=md5sums-$(date +%s)
+LOCK_FILE=$LOCAL_DOWNLOAD_DIR/.lock
+TIME=$(date +%s)
+LIST_FILE=$LOCAL_DOWNLOAD_DIR/filelist-$TIME
+
+SFTP_LINE_FILTER='\.log\.gz$'
+
+# Just to be sure
+mkdir -p $LOCAL_DOWNLOAD_DIR
+mkdir -p $LOCAL_LOGS_DIR
 
 # Create lockfile, to avoid running the scanner
 if [ -e $LOCK_FILE ]; then
@@ -27,36 +31,47 @@ fi
 touch $LOCK_FILE
 
 # Get the files from SFTP
-ssh $AKAMAI_USER@$AKAMAI_HOST "cd $AKAMAI_LOGS_DIR && $AKAMAI_MD5 *.gz" > $LOCAL_DOWNLOAD_DIR/$CHECKSUM_FILE
+echo 'ls -l *.gz' | sftp $AKAMAI_USER@$AKAMAI_HOST:$AKAMAI_LOGS_DIR | grep -e $SFTP_LINE_FILTER > $LIST_FILE
 sftp $AKAMAI_USER@$AKAMAI_HOST:$AKAMAI_LOGS_DIR/*.gz $LOCAL_DOWNLOAD_DIR
 
 # RSYNC the files to my backup machine
-rsync -az --exclude=.lock $LOCAL_DOWNLOAD_DIR/ $BACKUP_USER@$BACKUP_HOST:$BACKUP_LOGS_DIR
+rsync -acz --exclude=.lock $LOCAL_DOWNLOAD_DIR/ $BACKUP_USER@$BACKUP_HOST:$BACKUP_LOGS_DIR
 
 # Remove the lockfile, to allow the scanner to run again
 rm $LOCK_FILE
 
-# Use checksum to verify I got the files correct
-cd $LOCAL_DOWNLOAD_DIR && $LOCAL_MD5 -c $CHECKSUM_FILE
-if [ $? -ne 0 ] ; then
-  echo "ERROR: Checksum between akamai and local copy failed."
-  exit 1
-fi
+# Check local files by gzip integrity and size
+cd $LOCAL_DOWNLOAD_DIR
+while read entry; do
+  # File under check
+  filename=$(echo $entry | awk '{print $9}')
 
-ssh $BACKUP_USER@$BACKUP_HOST "cd $BACKUP_LOGS_DIR && $BACKUP_MD5 -c $CHECKSUM_FILE"
-if [ $? -ne 0 ] ; then
-  echo "ERROR: Checksum between akamai and backup copy failed."
-  exit 1
-fi
+  # Checking gzip integrity
+  gzip -t $filename
+  if [ $? -ne 0 ] ; then
+    echo "ERROR($TIME): GZIP integrity check of '$filename' failed."
+    exit 1
+  fi
 
-# Delete the files on the akamai
-for log_file in $(awk '{print $2}' $LOCAL_DOWNLOAD_DIR/$CHECKSUM_FILE); do
-  ssh $AKAMAI_USER@$AKAMAI_HOST "rm $AKAMAI_LOGS_DIR/$log_file"
+  remote_size=$(echo $entry | awk '{print $5}')
+  local_size=$(ls -l $filename | awk '{print $5}')
+  if [ $remote_size -ne $local_size ]; then
+    echo "ERROR($TIME): Filesize of '$filename' differs between local and akamai."
+  exit 1
+  fi
+done < $LIST_FILE
+
+# Delete the files on akamai
+for log_file in $(awk '{print $9}' $LIST_FILE); do
+  sftp $AKAMAI_USER@$AKAMAI_HOST:$AKAMAI_LOGS_DIR <<END_SCRIPT
+  rm $log_file
+END_SCRIPT
 done
-rm $LOCAL_DOWNLOAD_DIR/$CHECKSUM_FILE
-ssh $BACKUP_USER@$BACKUP_HOST "rm $BACKUP_LOGS_DIR/$CHECKSUM_FILE"
 
 # Move the files into the log directory
-for log_file in $(awk '{print $2}' $LOCAL_DOWNLOAD_DIR/$CHECKSUM_FILE); do
+for log_file in $(awk '{print $9}' $LIST_FILE); do
   mv $LOCAL_DOWNLOAD_DIR/$log_file $LOCAL_LOGS_DIR/
 done
+
+# Cleanup Tempfiles
+rm $LIST_FILE
