[#54213626] Backup check shouldn't silent fail
Raise an UNKNOWN if unable to check the backup directories. Which I think
we'll find is all the time, because NRPE runs the check as UID `nagios` and
the directories are owned by `govuk-backup`. Currently an error is raised to
STDERR but an `OK` message and exit code 0 is used anyway. This will surface
the error for us to later fix - which may involve rewriting this plugin.

diff --git a/modules/backup/files/check_backup_age b/modules/backup/files/check_backup_age
--- a/modules/backup/files/check_backup_age
+++ b/modules/backup/files/check_backup_age
@@ -1,8 +1,18 @@
 #!/bin/bash
+set -e
+set -o pipefail
+
+function error() {
+  echo "UNKNOWN: Unable to read backup directories"
+  exit 2
+}
+trap error ERR
+
 count=0
 message=""
 
-for backupinfo in `find /data/backups/ -name BACKUPINFO`; do
+dirs=$(find /data/backups/ -name BACKUPINFO)
+for backupinfo in $dirs; do
    directory=${backupinfo%%/BACKUPINFO}
    date=`cat $backupinfo | sed -e 's/Date: //g'`
    today=`date +%s`; 
