Update swarm logic
My original logic assumed a single manager. If the manager dies, then
all state is lost and the swarm must be recreated and all apps would
need to be redeployed.

As such, we should have at least 3 managers. This allows the logic for a
new manager to join a cluster if it dies and is recreated.

diff --git a/modules/govuk_docker/templates/swarm_manager.erb b/modules/govuk_docker/templates/swarm_manager.erb
--- a/modules/govuk_docker/templates/swarm_manager.erb
+++ b/modules/govuk_docker/templates/swarm_manager.erb
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Lightweight wrapper for dynamically creating a new cluster as manager role
+# Wrapper for dynamically creating a new cluster as manager role
 #
 export ETCDCTL_API=3
 exec 1> >(logger -s -t $(basename $0)) 2>&1
@@ -13,9 +13,9 @@ if [[ -z $CLUSTER_NAME ]]; then
   exit 1
 fi
 
-CLUSTER_WORKER_TOKEN=$($ETCDCTL_BIN get --print-value-only $CLUSTER_NAME/worker/token)
-CLUSTER_MANAGER_TOKEN=$($ETCDCTL_BIN get --print-value-only $CLUSTER_NAME/manager/token)
-CLUSTER_MANAGER_IP=$($ETCDCTL_BIN get --print-value-only $CLUSTER_NAME/manager/ip)
+CLUSTER_WORKER_TOKEN=$($ETCDCTL_BIN get --print-value-only $CLUSTER_NAME/cluster/token/worker)
+CLUSTER_MANAGER_TOKEN=$($ETCDCTL_BIN get --print-value-only $CLUSTER_NAME/cluster/token/manager)
+CLUSTER_ID=$($ETCDCTL_BIN get --print-value-only $CLUSTER_NAME/cluster/id)
 
 function create_cluster {
   echo "Creating cluster ${CLUSTER_NAME}"
@@ -25,31 +25,58 @@ function create_cluster {
   WORKER_TOKEN=$(docker swarm join-token worker -q)
   MANAGER_TOKEN=$(docker swarm join-token manager -q)
 
-  echo "Updating etcd: ${CLUSTER_NAME}/manager/ip"
-  $ETCDCTL_BIN put $CLUSTER_NAME/manager/ip $(hostname -i)
-  echo "Updating etcd: ${CLUSTER_NAME}/manager/token"
-  $ETCDCTL_BIN put $CLUSTER_NAME/manager/token $MANAGER_TOKEN
-  echo "Updating etcd: ${CLUSTER_NAME}/worker/token"
-  $ETCDCTL_BIN put $CLUSTER_NAME/worker/token $WORKER_TOKEN
+  echo "Publishing manager node: ${CLUSTER_NAME}/managers/$(hostname)"
+  $ETCDCTL_BIN put $CLUSTER_NAME/managers/$(hostname) $(hostname -i)
+
+  echo "Publishing token: ${CLUSTER_NAME}/cluster/token/manager"
+  $ETCDCTL_BIN put $CLUSTER_NAME/cluster/token/manager $MANAGER_TOKEN
+
+  echo "Publishing token: ${CLUSTER_NAME}/cluster/token/worker"
+  $ETCDCTL_BIN put $CLUSTER_NAME/cluster/token/worker $WORKER_TOKEN
+
+  echo "Publishing Cluster ID"
+  $ETCDCTL_BIN put $CLUSTER_NAME/cluster/id "$(date +%s)_${CLUSTER_NAME}"
 }
 
 if ! docker info 2>/dev/null| grep -qw "Swarm: active"; then
 
-  echo "Checking for active manager elsewhere"
-  # If there is a manager IP being returned, see if the cluster is available to join
-  if [[ $CLUSTER_MANAGER_IP != "" ]]; then
-    echo "Joining cluster $CLUSTER_NAME"
-    docker swarm join \
-      --token $CLUSTER_WORKER_TOKEN \
-      $CLUSTER_MANAGER_IP:2377
-
-    if [[ $? == 0 ]]; then
-      exit 0
+  echo "Checking for active manager elsewhere..."
+  # See if there are any active managers available to join
+  for manager in $($ETCDCTL_BIN get --prefix --print-value-only $CLUSTER_NAME/managers); do
+    if [[ $manager == "$(hostname -i)" ]]; then
+      echo "IP my own, yet I am not part of any active cluster. Skipping"
+      $ETCDCTL_BIN del $CLUSTER_NAME/managers/$(hostname)
     else
-      echo "Unable to join cluster on IP ${CLUSTER_MANAGER_IP}, attempting to recreate"
-      create_cluster
+      echo "Attempting to join manager IP ${manager}"
+      docker swarm join \
+        --token $CLUSTER_MANAGER_TOKEN \
+        $manager:2377
+
+      if [[ $? == 0 ]]; then
+        echo "Successfully joined cluster!"
+
+        echo "Updating etcd: ${CLUSTER_NAME}/managers/$(hostname)"
+        $ETCDCTL_BIN put $CLUSTER_NAME/managers/$(hostname) $(hostname -i)
+
+        exit 0
+      fi
     fi
-  else
-    create_cluster
-  fi
+  done
+
+  echo "Cannot find cluster to join, creating"
+  create_cluster
+  echo "Created cluster with ID $($ETCDCTL_BIN get --print-value-only $CLUSTER_NAME/cluster/id)"
+else
+  for worker in $($ETCDCTL_BIN get $CLUSTER_NAME/workers --prefix --keys-only |cut -d "/" -f); do
+    if [[ -z "docker node ls |grep ${worker}" ]]; then
+      echo "Maintenance: ${worker} not in swarm, removing from etcd"
+      $ETCDCTL_BIN del $CLUSTER_NAME/workers/${worker}
+    fi
+  done
+  for manager in $($ETCDCTL_BIN get $CLUSTER_NAME/managers --prefix --keys-only |cut -d "/" -f); do
+    if [[ -z "docker node ls |grep ${manager}" ]]; then
+      echo "Maintenance: ${manager} not in swarm, removing from etcd"
+      $ETCDCTL_BIN del $CLUSTER_NAME/managers/${manager}
+    fi
+  done
 fi
diff --git a/modules/govuk_docker/templates/swarm_worker.erb b/modules/govuk_docker/templates/swarm_worker.erb
--- a/modules/govuk_docker/templates/swarm_worker.erb
+++ b/modules/govuk_docker/templates/swarm_worker.erb
@@ -1,8 +1,7 @@
 #!/bin/bash
 #
-# Lightweight wrapper for dynamically managing a Docker Swarm worker
+# Wrapper for dynamically managing a Docker Swarm worker
 #
-set -e
 exec 1> >(logger -s -t $(basename $0)) 2>&1
 export ETCDCTL_API=3
 CLUSTER_NAME=$1
@@ -14,13 +13,46 @@ if [[ -z $CLUSTER_NAME ]]; then
   exit 1
 fi
 
-CLUSTER_WORKER_TOKEN=$($ETCDCTL_BIN get --print-value-only $CLUSTER_NAME/worker/token)
-CLUSTER_MANAGER_IP=$($ETCDCTL_BIN get --print-value-only $CLUSTER_NAME/manager/ip)
+CLUSTER_WORKER_TOKEN=$($ETCDCTL_BIN get --print-value-only $CLUSTER_NAME/cluster/token/worker)
+CLUSTER_MANAGER_IP=$($ETCDCTL_BIN get --print-value-only $CLUSTER_NAME/cluster/token/manager)
+CURRENT_CLUSTER_ID=$($ETCDCTL_BIN get --print-value-only $CLUSTER_NAME/workers/$(hostname)/cluster)
+CLUSTER_ID=$($ETCDCTL_BIN get --print-value-only $CLUSTER_NAME/cluster/id)
+
+if docker info 2>/dev/null| grep -qw "Swarm: active"; then
+  if [[ $CURRENT_CLUSTER_ID != $CLUSTER_ID  ]]; then
+    echo "I do not appear to be part of the right cluster, leaving"
+    docker swarm leave
+    sleep 10
+  fi
+fi
+
+if docker info 2>/dev/null| grep -qw "Swarm: error"; then
+  echo "Swarm in error state, leaving to rejoin"
+  docker swarm leave
+  sleep 10
+fi
 
 if ! docker info 2>/dev/null| grep -qw "Swarm: active"; then
   echo "Joining cluster ${CLUSTER_NAME}"
-  echo "Manager IP: ${CLUSTER_MANAGER_IP}"
-  docker swarm join \
-    --token $CLUSTER_WORKER_TOKEN \
-    $CLUSTER_MANAGER_IP:2377
+  echo "Checking for active managers to join"
+  for manager in $($ETCDCTL_BIN get --prefix --print-value-only $CLUSTER_NAME/managers); do
+    docker swarm join \
+      --token $CLUSTER_WORKER_TOKEN \
+      $manager:2377
+
+    if [[ $? == 0 ]]; then
+      echo "Successfully joined cluster!"
+
+      echo "Publishing worker IP"
+      $ETCDCTL_BIN put $CLUSTER_NAME/workers/$(hostname)/ip $(hostname -i)
+
+      echo "Publishing which cluster I am part of"
+      $ETCDCTL_BIN put $CLUSTER_NAME/workers/$(hostname)/cluster $CLUSTER_ID
+
+      exit 0
+    fi
+  done
+
+  echo "Error: haven't been able to join any clusters"
+  exit 1
 fi
